FROM python:3.8
LABEL maintainer="KenJoel Muigai"

COPY . /app
COPY requirements.txt /app/requirements.txt
WORKDIR /app
RUN pip install -r requirements.txt

# command to run on container start
CMD [ "python", "app/backend/main.py" ]
